---
title: Group Project Deliverable 4
date: 10/9/2023
author: Rachel Farzan, Javeria Hanif, Feyza Sakin
format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true

---

# ER Diagrams
### Chen Notation Diagram

```{dot}
graph ER {
    layout=neato;
    scale=2;
    node [shape=box]; playlist, album, song, user, artist
    node [shape=ellipse]; playlist_ID, playlist_name, user, description, album_ID, album_name, record_label, genre, song_ID, song_name, tempo, key, user_ID, user_name, password, account_type, plays, song_number, album_classification, playlist_description, album_duration, song_duration, release_date, birth_date, debut_date,playlist_duration, artist_name, artist_ID, follower_count, following_count
    node [shape=diamond,style=filled,color=lightgrey]; has, "has ",is, " has", " has ", "  has ", following
    
    playlist -- has [label="0...n",len=1.00]
    has -- song [label="1...n",len=1.00]

    playlist -- "has " [label="0...n",len=1.00]
    "has " -- user [label="1",len=1.00]

    artist -- is [label="0...1",len=1.00]
    is -- user [label="1",len=1.00]

    artist -- " has" [label="1",len=1.00]
    " has" -- album [label="1...n",len=1.00]

    album -- " has " [label="1",len=1.00]
    " has " -- song [label="1...n",len=1.00]

    artist -- "  has " [label="1...n",len=1.00]
    "  has " -- song [label="1...n",len=1.00]

    user -- following [label="0...n",len=1.00]
    following -- user [label="0...n",len=1.00]
    
    playlist -- playlist_ID
    playlist -- playlist_name
    playlist -- song_number
    playlist -- playlist_description
    playlist -- playlist_duration
    
    album -- album_ID
    album -- record_label
    album -- album_classification
    album -- genre
    album -- album_name
    album -- album_duration
    album -- release_date

    song -- song_ID
    song -- song_name
    song -- tempo
    song -- key
    song -- plays
    song -- song_duration

    user -- user_ID
    user -- user_name
    user -- account_type
    user -- password
    user -- follower_count
    user -- following_count

    artist -- artist_ID
    artist -- description
    artist -- birth_date
    artist -- debut_date
    artist -- artist_name

} 
```

### Crow's Foot Diagram
```{mermaid}
erDiagram
    PLAYLIST }o--o{ SONG : has
    ALBUM ||--|{ SONG : has
    ARTIST }|--|{ ALBUM : has
    USER ||--o{ PLAYLIST : has
    ARTIST |o--|| USER : is
    ARTIST }|--|{ SONG : has

    PLAYLIST{
        string ID PK
        string name
        string user_ID FK
        string description
        int duration
        int song_number
    }

    ALBUM{
        string ID PK
        string name
        string record_label
        string genre
        date release_date
        string classification
        int duration
        string artist_ID FK
    }

    SONG{
        string ID PK
        string name
        int tempo
        string key
        int plays
        int duration
        string artist_ID FK
        string album_ID FK
    } 

    USER {
        string ID PK
        string user_name
        string password
        string account_type
        int follower_count
        int following_count
    }

    ARTIST {
        string ID PK
        string artist_name
        date birth_date
        string description
        date debut_date
    }


```

### Design Notes

One thought that we had was to possibly have an album be a more specific type of playlist (a playlist that only an artist can make). However, we also wanted ot include features that only playlists could have (i.e. discriptions). It also seemed unnecessary to connect albums and playlists, so we ultimately decided not to.

We also had to consider which relationships to make many-to-many. Songs are often by multiple artist, so we made that relationship many-to-many. Though albums aren't as often by multiple artist, we thought it would be the most consistent to also make that relationship many-to-many. Though songs can also be on multiple albums, they often show up as separate songs on music apps like Spotify, so we decided to keep that relationship as one-to-many.

[Add other trade-offs]

# Relational Schemas

user (ID [PK], user_name [NOT_NULL, UNIQUE], password [NOT_NULL], account_type [(free, premium, artist)])

artist (ID [PK], name [NOT_NULL], birth_date [NOT_NULL], description, debut_date [NOT_NULL])

song (ID [PK], name [NOT_NULL], tempo, key, plays [NOT_NULL], duration [NOT_NULL], artist_ID [FK], album_ID [FK])

album (ID [PK], name [NOT_NULL], record_label [NOT_NULL], genre, release_date [NOT_NULL], classification [NOT_NULL], duration [NOT_NULL], artist_ID[FK])

playlist (ID [PK], name [NOT_NULL], description, duration [NOT_NULL], song_number [NOT_NULL], user_ID[FK])

artist_song (ID [PK], artist_ID[FK], song_ID[FK])

        FK(artist_ID) references artist.ID

        FK(song_ID) references song.ID

artist_album (ID [PK], artist_ID[FK], album_ID[FK])

        FK(artist_ID) references artist.ID

        FK(album_ID) references album.ID

playlist_song (ID [PK], playlist_ID[FK], song_ID[FK])

        FK(playlist_ID) references playlist.ID
    
        FK(song_ID) references song.ID


following (ID [PK], follower_ID[FK], following_ID[FK])

        FK(follower_ID) references user.ID

        FK(following_ID) references user.ID

# Functional Dependencies

user (ID, user_name, password, account_type)

        ID -> user_name, password, account_type

artist (ID, name, birth_date, description, debut_date)

        ID -> name, birth_date, description, debut_date

song (ID, name, tempo, key, plays, duration, artist_ID, album_ID)

        ID -> name, tempo, key, plays, duration, artist_ID, album_ID

album (ID, name, record_label, genre, release_date, classification, duration, artist_ID)

        ID -> name, record_label, genre, release_date, classification, duration, artist_ID

playlist (ID, name, description, duration, song_number, user_ID)

        ID -> name, description, duration, song_number, user_ID

artist_song (ID, artist_ID, song_ID)

        ID -> artist_ID, song_ID

artist_album (ID, artist_ID, album_ID)

        ID -> artist_ID, album_ID

playlist_song (ID, playlist_ID, song_ID)

        ID -> playlist_ID, song_ID

following (ID, follower_ID, following_ID)

        ID -> follower_ID, following_ID

#### Normalization Notes

Our relations are already in BCNF, as each relation consist of 1 functional dependency, where the candidate key determines everything else in the relation.

# Sample Data

#### user (ID, user_name, password, account_type)

| user_ID | username | password | account_type |
| --- | --- | --- | --- |
| 1 | user1 | pass1 | free |
| 2 | user2 | pass2 | premium |
| 3 | artist1 | pass3 | artist |
| 4 | user3 | pass4 | free |
| 5 | user4 | pass5 | premium |
| 6 | artist2 | pass6 | artist |
| 7 | user5 | pass7 | free |
| 8 | user6 | pass8 | premium |
| 9 | artist3 | pass9 | artist |
| 10 | user7 | pass10 | free |

#### artist (ID, name, birth_date, description, debut_date)

|   ID   |     Name     |  Birth Date  |       Description       |  Debut Date  |
|-------|-------------|--------------|-------------------------|-------------|
|   3 | Artist Name 1| 1990-04-15   | Description 1 | 2010-08-20  |
|   6 | Artist Name 2| 1985-11-30   | Description 2 | 2005-06-12  |
|   9 | Artist Name 3| 1995-07-25   | Description 3 | 2012-03-05  |
|   11 | Artist Name 4| 1982-02-10   | Description 4 | 2000-09-18  |
|   12 | Artist Name 1| 1988-09-05   | Description 5 | 2008-12-24  |
|   15 | Artist Name 5| 1990-07-25   | NULL | 2011-06-05  |
|   16 | Artist Name 6| 1985-11-30   | Description 6 | 2007-10-02  |
|   20 | Artist Name 7| 1990-01-14   | Description 7 | 2015-03-09  |
|   21 | Artist Name 8| 1970-08-20   | Description 1 | 2020-09-25  |
|   22 | Artist Name 9| 1989-09-18   | Description 8 | 2008-06-24  |

#### song (ID, name, tempo, key, plays, duration, artist_ID, album_ID)

|   ID   |       Name       | Tempo  |   Key   |  Plays  | Duration | Artist ID | Album ID |
|-------|------------------|--------|---------|---------|----------|-----------|----------|
|   1   |  Song Name 1     |  120   |   C#    |  2500   |  3:45    |    1    |    1     |
|   2   |  Song Name 2     |  NULL    |   G     |  3200   |  4:10    |    2    |    2     |
|   3   |  Song Name 3     |  110   |   D     |  1800   |  3:20    |    2    |    3     |
|   4   |  Song Name 4     |  75    |   A     |  3100   |  4:55    |    3    |    4     |
|   5   |  Song Name 5     |  130   |   E     |  2800   |  3:30    |    4    |    5     |
|   6   |  Song Name 6     |  100   |   D    |  30000   |  3:10    |    5    |    6     |
|   7   |  Song Name 6     |  100    |   D     |  30000   |  3:10    |    5    |    7     |
|   8   |  Song Name 3     |  90   |   NULL     |  2200   |  3:40    |    6    |    8     |
|   9   |  Song Name 7     |  80    |   A#     |  3100   |  2:14    |    1    |    1     |
|   10   |  Song Name 8     |  125   |   E     |  2800   |  3:01    |    7    |    9     |

#### album (ID, name, record_label, genre, release_date, classification, duration, artist_ID)

|   ID   |      Name      | Record Label |    Genre    | Release Date | Classification | Duration | Artist ID |
|-------|----------------|--------------|-------------|--------------|----------------|----------|-----------|
|   1   |  Album Name 1  | Label 1      | Rock        | 2023-01-15   | EP           | 45:30    |    1    |
|   2   |  Album Name 2  | Label 2      | Pop         | 2022-05-20   | Album       | 37:45    |    2    |
|   3   |  Album Name 3  | Label 3      | Hip-Hop     | 2021-11-10   | Single         | 52:15    |    3    |
|   4   |  Album Name 4  | Label 4      | Jazz        | 2023-03-02   | Collection           | 61:10    |    4    |
|   5   |  Album Name 5  | Label 5      | Electronic  | 2022-08-17   | Album       | 49:20    |    5    |
|   6   |  Album Name 1  | Label 1      | Rock        | 2023-01-15   | EP           | 45:30    |    1    |
|   7   |  Album Name 6  | Label 1      | NULL         | 2022-05-20   | Album       | 37:45    |    6    |
|   8   |  Album Name 7  | Label 6      | Classical     | 2021-11-10   | Single         | 3:15    |    7    |
|   9   |  Album Name 8  | Label 7      | Jazz        | 2023-03-02   | Collection           | 61:10    |    8    |
|   10   |  Album Name 9  | Label 8      | R&B  | 2022-08-17   | Album       | 49:20    |    5    |

#### playlist (ID, name, description, duration, song_number, user_ID)

|   ID   |      Name      |     Description    | Duration | Song Number | User ID |
|-------|----------------|--------------------|----------|------------|---------|
|   1   | Playlist Name 1 | Description 1     | 2:30:15  |    20      |   1   |
|   2   | Playlist Name 2 | Description 2     | 1:45:40  |    15      |   1   |
|   3   | Playlist Name 3 | Description 3     | 3:10:22  |    30      |   2   |
|   4   | Playlist Name 4 | Description 4     | 1:15:50  |    12      |   3   |
|   5   | Playlist Name 5 | Description 5     | 4:05:30  |    40      |   4   |
|   6   | Playlist Name 5 | NULL     | 2:30:15  |    20      |   5   |
|   7   | Playlist Name 6 | Description 6     | 0:3:40  |    1      |   6   |
|   8   | Playlist Name 7 | Description 3     | 3:53:22  |    25      |   6   |
|   9   | Playlist Name 8 | Description 7     | 1:06:50  |    10      |   6   |
|   10   | Playlist Name 9 | Description 8     | 5:05:30  |    51      |   7   |


#### artist_song (ID, artist_ID, song_ID)

|   ID   | Artist ID | Song ID |
|-------|----------|---------|
|   1   |   1    |   1     |
|   2   |   1    |   2     |
|   3   |   2    |   2     |
|   4   |   2    |   3     |
|   5   |   2    |   4     |
|   6   |   2    |   5     |
|   7   |   3    |   1     |
|   8   |   3    |   6     |
|   9   |   4    |   7     |
|   10   |   4    |   8     |

#### artist_album (ID, artist_ID, album_ID)

|   ID   | Artist ID | Album ID |
|-------|----------|---------|
|   1   |   1    |   1     |
|   2   |   1    |   2     |
|   3   |   2    |   2     |
|   4   |   2    |   3     |
|   5   |   2    |   4     |
|   6   |   2    |   5     |
|   7   |   3    |   1     |
|   8   |   3    |   6     |
|   9   |   4    |   7     |
|   10   |   4    |   8     |


#### playlist_song (ID, playlist_ID, song_ID)

|   ID   | Playlist ID | Song ID |
|-------|----------|---------|
|   1   |   1    |   1     |
|   2   |   1    |   2     |
|   3   |   1    |   3     |
|   4   |   1    |   4     |
|   5   |   2    |   1     |
|   6   |   2    |   3     |
|   7   |   2    |   5     |
|   8   |   2    |   6     |
|   9   |   4    |   7     |
|   10   |   4    |   8     |

####  following (ID, follower_ID, following_ID)

|   ID   | Follower ID | Following ID |
|-------|----------|---------|
|   1   |   1    |   1     |
|   2   |   1    |   2     |
|   3   |   1    |   3     |
|   4   |   1    |   4     |
|   5   |   1    |   5     |
|   6   |   2    |   1     |
|   7   |   2    |   3     |
|   8   |   2    |   6     |
|   9   |   2    |   7     |
|   10   |   4    |   8     |